### PR TITLE
change fpath to path

### PR DESCRIPTION
**Pull request by brandonblock**
Discovered this undefined argument name while tripping an error with my messed-up gopath

### CODE REVIEW

**Comment by zchee** [comment]
LGTM, I'm missed :P

**Comment by zchee** [comment]
@brandonblock Thanks!! merged.

**Comment by brandonblock** [comment]
Cool! Thanks for working on such a useful project!

Now only if there was a language that caught undefined variables at compile time...

**Comment by zchee** [comment]
@brandonblock 

> Now only if there was a language that caught undefined variables at compile time...

Yeah.
The dynamically languages sometimes difficult, but that's why _"test"_ is important. but now, deoplete-go is no testing process :P
Although there is no direct relationship, I am considering introducing `mypy`. I want to _"type"_... lol

**Pull request merged**
