### PR TITLE
quick readme update for imports

### PR DESCRIPTION
**Pull request by nhooyr**

### CODE REVIEW

**Comment by nhooyr** [comment]
Actually never mind, sorting based on `import` completions doesn't matter. When `gocode` detects that you are inside a import statement it only returns import completions. Lets just revert adding import to the class sorting.

**Comment by nhooyr** [comment]
never mind, no need for an update, I misread the readme. Those are crossed out.

**Comment by zchee** [comment]
@nhooyr Reverted: https://github.com/zchee/deoplete-go/commit/055e5d5b51a63279cad529aa0a93d8524bb99f19

**Comment by nhooyr** [comment]
great

**Pull request closed without merging**
