### PR TITLE
Makefile fixes, Go version bump

### PR DESCRIPTION
**Pull request by rvolosatovs**

### CODE REVIEW

**Comment by Shougo** [comment]
LGTM.

@zchee Ping.

**Comment by Shougo** [comment]
I will try it later.

**Comment by zchee** [comment]
@rvolosatovs @Shougo Sorry for late reply :(
I'll also try to check it later.

**Comment by tmichaud314** [comment]
@rvolosatovs @zchee Would it be possible to bump this to Go 1.9.5 (latest)? Since the Go data is so outdated, would it be possible to get this merged sooner? Appreciate it!!

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
