### PR TITLE
completion improvements

### LINKED ISSUE #21: completion after a package is unintuitive
For example (`|` is the cursor.)

``` go
package main

import (
    "go/parser"
)

func main() {
    pars|
}
```

Currently if you complete at that point and move down to `package parser` it will look like

``` go
package main

import (
    "go/parser"
)

func main() {
    parser.|
}
```

But now you have to first press `<c-y>` to accept the completion before the completion can continue on the functions of the `parser` package.

Instead after completing `package parser` it should not insert a period. Instead:

``` go
package main

import (
    "go/parser"
)

func main() {
    parser|
}
```

Then type the period and all is good. Its much more intuitive then pressing `<c-y>`.

### PR DESCRIPTION
**Pull request by nhooyr**
This fixes #21, #20 and #17

Package completion does not add a period after as it is unintuitive.
Type info for vars/types is now shown. Gocode and neovims column
measures are different. We need to subtract 1 from offset for gocode to
correctly understand. Lastly the completion names are not aligned.

### CODE REVIEW

**Comment by zchee** [comment]
@nhooyr Fix show type info looks good.

But why unnecessary is dot completion and aligned?
I am a troublesome to type the dot. and It will be slow to write the code.
Also does not aligned of class is too creepy.

**Comment by nhooyr** [comment]
@zchee Its kinda of the same problem as #7 

If the dot is typed automatically, you can't see all of the completion options immediately. You have to press `<c-y>` or delete it and enter it again. Or you continue typing. I prefer this behaviour. I described it in more detail with #21

I also found another bug that I'm taking a look at, I'll just include the fix into this pull request.

As for the alignment, its just what I'm used to. Previously vim-go, ycm and gocode didn't align the class so its likely what most other people are used to as well.

**Comment by zchee** [comment]
@nhooyr Sorry, I do not understand all.

>  you can't see all of the completion options immediately

What is `all of the completion options`?
That means `parser` package functions? e.g. `ParseDir()` `ParseExpr()`

Meaning you said, typed `par`, and select `parser` and hit `<C-y>`, but `parser` functions does not appear.
Therefore, displaying `parser` functions need remove the dot, and retyping dot.
Correct?

**Comment by nhooyr** [comment]
@zchee yes the parser package functions. But after I hit `<c-y>` they do appear. Its just that the typing the period to get them to appear is more intuitive (it's like that in other IDE's and previous go completion plugins). Instead now you have to press `<c-y>` (which works) OR remove and then retype.

**Comment by nhooyr** [comment]
Fixed. The offset for gocode is 1 behind vims offset. You can check it yourself by running gocode as

```
gocode -s -debug
```

Then try completing this file (`|` is the cursor)

``` go
package main

import (
    "go/parser"
    "go/token"
)

func main() {
    parser.ParseFile(token.|)
}
```

It won't complete properly because it thinks you are after the `)` but you are really after the `.`. Take a look at the `gocode` debug output to see.

Here is how the gocode debug output looks without this commit (`#` is the cursor)

``` go
package main

import (
        "go/parser"
        "go/token"
)

func main() {
        parser.ParseFile(token.)#
}
```

Now fixed the output (offset -1) will be

``` go
package main

import (
        "go/parser"
        "go/token"
)

func main() {
        parser.ParseFile(token.#)
}
```

**Comment by zchee** [comment]
@nhooyr got it.

> yes the parser package functions. But after I hit <c-y> they do appear. Its just that the typing the period to get them to appear is more intuitive (it's like that in other IDE's and previous go completion plugins). Instead now you have to press <c-y> (which works) OR remove and then retype.

That problem is due to your environment.
It worked my environment.

`deoplete.nvim` is asynchronous call source plugin.
So If use the low spec PC, or When pressure on the CPU, or something other plugin blocking `deoplete.nvim`, or etc... (I'm not saying your PC is a low spec)
In this situation, will occur you said behavior.
Maybe not caught up with the speed at which the dot is automatically input.

However, It is troublesome better things to remove the dot and retype dot than to manually insert dot.
So I will implement setting value. Also aligned class.
WDYT?
If you agreed, please fix PR.

>  The offset for gocode is 1 behind vims offset.

Good catch. that is a bug. Thanks!

**Comment by zchee** [comment]
@nhooyr FYI, https://asciinema.org/a/35756

**Comment by nhooyr** [comment]
@zchee 

Nooo. Nothing to do with specs. This isn't a bug or a problem. Its just about which is easier to use. For me, not completing the period and typing it after is easier. For you, pressing `<c-y>` to complete is easier. Most other IDE's use the method without auto inserting the period.

I'll upload an asciinema as well to show you what I mean. How long will you be up?

**Comment by zchee** [comment]
@nhooyr I wait forever for you upload asciinema.

**Comment by nhooyr** [comment]
@zchee 
Ok first, this is how it currently works.

https://asciinema.org/a/7vt8kie2bc6ddcz56ujccx43n

I have to press `<c-y>` to show the completion options.

Now here is my version.

https://asciinema.org/a/2apb7zat1g9p9ucd7thz7j7e0

I only have to select the package, then press the period and continue typing.

So yea I can revert it if you create an option for this and the alignment, no problem.

**Comment by zchee** [comment]
@nhooyr Oh, Now I understand! That's correct.
caused by different select of completion by you and me(?)

Sorry for It was too contain their preferences. and Thank you to long discuss.

I will create on/off option, also alignment.
and, add the user setting as long as the performance permit. `abbr`, `kind`, `menu`...

**Comment by fatih** [comment]
@nhooyr the `.` was also problematic for me but in my case I don't need to press `c-y`. It just is re-triggered. I wonder if it's because of some settings. Like `noinsert` or `noselect` ? I'm not sure but it just works for me.

**Comment by nhooyr** [comment]
@fatih i think its noinsert but I'll look it all over tomorrow.

@zchee I can add the options and all the documentation myself tomorrow. I'm gonna sleep now.

**Comment by nhooyr** [comment]
@fatih wait are you typing after the period. Or do you just select the package and bam it switches? It should only switch if you accept the package completion.

Also I'll stay up anyway and do it.

**Comment by fatih** [comment]
I'm not typing anything, the completion menu comes automatically. After that I can go and select another item.

**Comment by zchee** [comment]
@nhooyr OK.
but `self.vim.vars` is occured error if `deoplete#sources#go#foo` is none (not set in `init.vim`).
Therefore I use `try...except`.
So I think better way set default value with vim-side. such as `autoload`.

**Comment by nhooyr** [comment]
@fatih idk, probably some little configuration detail we're forgetting.

@zchee i'll do that.

**Comment by fatih** [comment]
@zchee can we merge this PR? Let's to the `.` adding in another one. I really need this. I can pull and merge it myself but prefer to use upstream.

**Comment by nhooyr** [comment]
Whatever you guys think is good. I'd rather sleep anyway.

**Comment by fatih** [comment]
@nhooyr go ahead and sleep. It's not wise to hack on something while half sleep :stuck_out_tongue:

**Comment by nhooyr** [comment]
Great idea. Good night.

**Comment by zchee** [comment]
lol

**Pull request closed without merging**
