### PR TITLE
Remove alignment feature. 'kind' instead of

### PR DESCRIPTION
**Pull request by zchee**

### CODE REVIEW

**Comment by zchee** [comment]
but, always "align" because separate `abbr` and `kind`

**Comment by svanharmelen** [comment]
@zchee can we revert this one? When using both the `go` and `buffer` sources, it gets spread out making is harder to read:

image

As you can see this makes it seem if `type` and `func` are the actual completion, just like the other `buffer` source completions. So you first look in that single row and when you cannot find what you expect you look more to the right and notice the additional info.

I liked it a lot more without this change 😞

**Comment by zchee** [comment]
@svanharmelen Hmm... Ok, I will revert.
Sorry 🙏

**Comment by svanharmelen** [comment]
Thanks!! 👍  😃

**Comment by zchee** [comment]
@svanharmelen I thought `abbr` and `kind` variable.
`abbr` is

> abbreviation of "word"; when not empty it is used in the menu instead of "word"

`kind` is

> single letter indicating the type of completion

by vim help.

Yes, `func, var, type, const` is not an abbreviation of "word".
Correct `abbr` is e.g.
`Printf func(format string, a ...interface{}) (n int, err error)`

but, correct `kind` is `func, var, type, const`.
And, I think "first abbr word is type" is the bad user interface.
Maybe it's behavior is `gocode` only.

So, I will discard the backward compatibility, will fix to this completion list order.

screenshot 2016-04-13 01 51 09

**Comment by svanharmelen** [comment]
@zchee that could be a good alternative... Would have to try it in order to know if it feels natural. I do notice that YouCompleteMe does use the default order as well:

image

But could be this solution works nicer... Have to try it first :wink:

**Pull request merged**
