### PR TITLE
Fixed regexp to work on returned values and arrays/maps/slices

### PR DESCRIPTION
**Pull request by nhooyr**
For example the following file (`|` is cursor)

``` go
package main

import (
    "net/http"
)

func main() {
    http.FileServer().|
}
```

also added `]` to make it work with maps/arrays.

### CODE REVIEW

**Comment by svanharmelen** [comment]
This does fix a use case I totally forgot about (see comment on issue #30), but it's not fully correct nor complete.

Have a meeting now, but will update the regex right after that! Thx for notifying!

**Comment by nhooyr** [comment]
@svanharmelen which use cases are left. I added maps/arrays/slices with `]`

**Comment by svanharmelen** [comment]
@nhooyr yeah I noticed :grinning: But just take a look at PR #35 and it's comment/explanation. That is a complete and correct solution matching exactly what is in the language specs.

**Comment by nhooyr** [comment]
Alright I updated it a tad as well now to make it more correct.

**Comment by nhooyr** [comment]
i'll close this in favour of #35

**Pull request closed without merging**
