### PR TITLE
Example config update and cleanup

### PR DESCRIPTION
**Pull request by nhooyr**
Updated the example config in the README for #4 and a bit of cleanup.

### CODE REVIEW

**Comment by zchee** [comment]
@nhooyr Thanks PR :)

but, conflicts `go.py`.
Could you rebase?

**Comment by nhooyr** [comment]
@zchee done, sorry about that I'm a bit new to working with git still. Didn't realize what I did wrong.

**Comment by nhooyr** [comment]
@zchee i created Shougo/deoplete.nvim#132 as the new issue. It has nothing to do with this plugin, it is a problem with deoplete.

**Comment by zchee** [comment]
@nhooyr Thanks reply.

I was set `min_pattern_length` and `rank` for users that are not good at the setting of neovim.
If not set `min_pattern_length` and `rank` by default, Its users will be confused because it does not work correctly.

However, that settings conflicted `deoplete` core now.
https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/init.vim#L145-L147
So, If not set `deoplete#ignore_source.go = ['omni']`, `deoplete-go` is not works.
but, At the stage where `deoplete-go` plugin is stabilized, @Shougo is scheduled to remove that code.

After that, a setting of neovim is not good at users do not need this setting.

``` vim
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources.go = ['omni']
```

So, I want to revert this PR https://github.com/zchee/deoplete-go/pull/2.
What do you think?

**Comment by nhooyr** [comment]
@zchee you don't need to set rank. the rank is by default 100. so it doesn't matter. as for the min_pattern_length it fine if you want to set it as a default or not. The user can edit it later anyway. go with however you like, but you definitely don't need to set the rank.

**Comment by zchee** [comment]
@nhooyr Ah, Sorry I missed.
I want to set of default `min_pattern_length` only.

So, I will revert to https://github.com/zchee/deoplete-go/pull/2. OK?

**Comment by nhooyr** [comment]
@zchee 
Thats fine, just add a note if they want to change it in the documentation. You do it like this:

``` vim
augroup deoplete 
    autocmd!
    au VimEnter * call deoplete#custom#set('go', 'min_pattern_length', 1)
augroup END
```

So even though you have a default set they can change it if they want.

**Comment by zchee** [comment]
@nhooyr Thanks.

# 

off topic.
It is my question.

Why need `autocmd`?
`deoplete` is auto parsing `deoplete#custom#set('go', 'min_pattern_length', 1)` in your `init.vim`.
So, not need `autocmd`.

If you want `deoplete#min_pattern_length = 1` only Go language, also not need that reason is (**'go'**, 'min_pattern_length', 1).

I tested `NeoBunldle` and `vim-plug`. but works correctly without `autocmd`

**Comment by nhooyr** [comment]
@zchee init.vim is loaded before the plugins so deoplete#custom#set doesn't exist as a function yet. You need autocmd so it runs it after the plugins are loaded. I'm not sure I got the second part? If you want it only for go, you change 'VimEnter *' to 'FileType go'.

**Comment by zchee** [comment]
@nhooyr Hmm...
I do not need `autocmd` in my init.vim.
neovim also deoplete possible autoloading `deoplete#custom#set` function.

See
- https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/custom.vim

My latest init.vim is here. I pushed now.
https://github.com/zchee/.nvim/blob/master/init.vim

https://github.com/zchee/.nvim/blob/master/init.vim#L373-L374 for use both of deoplete and ycm.
It is not related to this matter.

If call `deoplete#custom#set` before set `rumtimepath`, Yes, it function not works.

**Comment by nhooyr** [comment]
@zchee yea you are right. in mine I do it before I set runtimepath.

**Comment by zchee** [comment]
@nhooyr :)
I will revert later.

Anyway, Thanks for PR and discuss!!

**Pull request closed without merging**
